### ISSUE TITLE
Follow up from .NET nanoFramework 

### ISSUE THREAD

**Issue by josesimoes** [microcompiler/microserver#1]
Hi,

Don't know if you are aware of .NET [nanoFramework](https://github.com/nanoframework). 
We would like to use your HTTP server and port it to nanoFramework.
Wanted to check with your first if that's OK with you.  

Thanks!

CC @piwi1263 @RoSchmiSec

**Comment by microcompiler** [comment]
Sure,  you are more then welcome to.  Let me know when it is done and I will update my readme with a link to it.

**Comment by josesimoes** [comment]
Awesome! We are on it.
