### ISSUE TITLE
Not compatible with VS2019

### ISSUE THREAD

**Issue by Gerardo-Sista** [microcompiler/microserver#2]
Hello,
I'm working on a microserver implementing various services. I found your library and want to use it (for DHCP and DNS mainly). It's the only one thas has both services.
I have the following questions:
- is this project abandoned? Cloning and opening in VS2019 returns incompatibility error.
- are DHCP and DNS services complete (all RFC implemented)?
Thank you for your work!

**Comment by microcompiler** [comment]
Unfortunately Microsoft .NET Micro Framework only supports  Microsoft's Visual Studio 2013.
